apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: game-2048
          image: 666709165403.dkr.ecr.eu-west-2.amazonaws.com/eks-2048-deployment:1.0
          ports:
            - containerPort: 80